### PR TITLE
run the server on hyechat.herokuapp.com and fix some bugs

### PR DESCRIPTION
**Pull request by otanim**

### CODE REVIEW

**Comment by fxfactorial** [comment]
YES!!!!

**Comment by otanim** [comment]
@fxfactorial please make sure description of the repository was updated from:
image
to http://hyechat.herokuapp.com

**Comment by otanim** [comment]
@fxfactorial for further continuously deployment I suggest you to give you a permission to access to the HyeChat's Heroku's control panel, from there you can setup ther server by the way of connecting heroku 2 github.

**Comment by fxfactorial** [comment]
@otanim edgar.factorial@gmail.com

I love this

**Comment by otanim** [comment]
@fxfactorial done, please check you're e-mail.

**Pull request merged**
